language: python
python:
  - 3.6
install:
  - make install
script:
  - make test
afetr_success:
  - curl -k -u $ZEROBUGUID:$ZEROBUGTOKEN --request POST -H "Content-Type:application/json" -d '{"pit":"131","targetid":"wYadXCTsAXQYrTi$7!lE1598385221","ci":"Travis CI","tipo":"14"}' https://zerobug.co/ScanTarget/
